FROM node:24

# Upgrade npm to the latest version that works with this Node
RUN npm install -g npm@latest

RUN npm --version

# Set the working directory inside the container
WORKDIR /workspaces/lawn-mower-card


