name: Release

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
    tags: [ 'v*.*.*' ]
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/test.yml
    concurrency:
      group: validate-group
      cancel-in-progress: true
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: ⬢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: 📦 Install Packages
        run: npm ci

      - name: 🏗 Build
        run: npm run build

      - name: 🚀 Release
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc \
          echo "//registry.npmjs.org/:always-auth=true" >> ~/.npmrc \
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
