name: Release

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
    tags: [ 'v*.*.*' ]
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/test.yml
#    concurrency:
#      group: validate-group
#      cancel-in-progress: true
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: ⬢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: 📦 Install Packages
        run: npm ci

      - name: Run build and get version
        id: build
        run: |
          OUTPUT=$(npm run build) 
          VERSION=$(echo $OUTPUT | grep -oP 'lawn-mower-card@\K[^ ]+') 
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV 
          echo "$VERSION"
      
      - name: Create Release
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          gh release create v${{ env.PACKAGE_VERSION }} \
            --repo="${GITHUB_REPOSITORY}" \
            --title="${{ env.PACKAGE_VERSION }}" \
            --notes="Release notes for v${{ env.PACKAGE_VERSION }}" \
            --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Upload Release Asset
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
          gh release upload v${{ env.PACKAGE_VERSION }} ./dist/lawn-mower-card.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          
