name: Release

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main
    tags: [ 'v*.*.*' ]
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/test.yml
#    concurrency:
#      group: validate-group
#      cancel-in-progress: true
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: ⬢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: 📦 Install Packages
        run: npm ci

      - name: 🏗 Build
        run: npm run build

#      - name: 🚀 Release
#        run: |
#          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc \
#          echo "//registry.npmjs.org/:always-auth=true" >> ~/.npmrc \
#          npx semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

#      - name: 🚀 Release
#        run: npm publish --access public
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get version
        id: package
        run: echo "PACKAGE_VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: ${{ env.PACKAGE_VERSION }}
          draft: true
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dist/lawn-mower-card.js
          asset_name: lawn-mower-card.js
          
          
